worker_processes 1;

events {
    worker_connections 1024;
}

http {
    types {
        text/html                             html;
        text/css                              css;
        application/javascript                js;
        application/json                      json;
        image/png                             png;
        image/jpeg                            jpg jpeg;
    }

    default_type  application/octet-stream;

    upstream gateway_service {
        server gateway-service:8088;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://gateway_service;
            proxy_set_header Host $host;
            proxy_set_header X-Forwarded-For $remote_addr;
            proxy_set_header X-Real-IP $remote_addr;
        }
    }
}
