worker_processes 1;

events {
    worker_connections 1024;
}

http {
    # 手动定义 MIME 类型
    types {
        text/html                             html;
        text/css                              css;
        application/javascript                  js;
        application/json                        json;
        image/png                              png;
        image/jpeg                             jpg jpeg;
    }

    default_type  application/octet-stream;

    upstream user_service {
        server user-service-1:8080;
        server user-service-2:8080;
    }

    upstream product_service {
    server product-service:8081 max_fails=3 fail_timeout=30s;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
            root /usr/share/nginx/html;
            try_files $uri $uri/ /index.html;
        }

        location /api/ {
            proxy_pass http://user_service;
            proxy_set_header Host $host;
        }

        location /api/products/ {
            proxy_pass http://product_service;
            proxy_set_header Host $host;
        }
    }
}