server:
  port: 8080 # 用户服务运行在 8080 端口

spring:
  application:
    name: user-service
  threads:
    virtual:
      enabled: true # 继续保持 Java 21 虚拟线程开启
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://rm-cn-swx4p26ot00019do.rwlb.rds.aliyuncs.com:3306/seckill_db?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai&useSSL=false
    username: dms_user_9bc05ec # 换成你的数据库用户名
    password: AYAKO0217sir@ # 换成你的数据库密码

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true # 开启驼峰命名转换